### ISSUE TITLE
permission denied error in hub container

### ISSUE THREAD

**Issue by bpfrd** [CERIT-SC/nbgrader-k8s#2]
Hello,

when creating a minikube with more than one node, I keep getting the below error:

```
$kubectl get pod
NAME READY STATUS RESTARTS AGE
hub-7dd77cd747-29sd5 0/1 CrashLoopBackOff 3 (37s ago) 2m10s
proxy-bffbd5c54-5x62h 1/1 Running 0 2m10s
```
```
$kubectl logs pod/hub-7dd77cd747-29sd5
[D 2023-12-12 11:33:46.056 JupyterHub application:902] Looking for /usr/local/etc/jupyterhub/jupyterhub_config in /srv/jupyterhub
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
Loading extra config: 00-extra-config
[E 2023-12-12 11:33:46.468 JupyterHub app:3382]
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/jupyterhub/app.py", line 3379, in launch_instance_async
await self.initialize(argv)
File "/usr/local/lib/python3.11/site-packages/jupyterhub/app.py", line 2857, in initialize
self.load_config_file(self.config_file)
File "/usr/local/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
return method(app, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/traitlets/config/application.py", line 950, in load_config_file
for (config, fname) in self._load_config_files(
File "/usr/local/lib/python3.11/site-packages/traitlets/config/application.py", line 909, in _load_config_files
config = loader.load_config()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/traitlets/config/loader.py", line 626, in load_config
self._read_file_as_dict()
File "/usr/local/lib/python3.11/site-packages/traitlets/config/loader.py", line 659, in _read_file_as_dict
exec(compile(f.read(), conf_filename, "exec"), namespace, namespace) # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/etc/jupyterhub/jupyterhub_config.py", line 497, in
exec(config_py)
File "", line 174, in
File "", line 215, in makedirs
File "", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/mnt/exchange/course1'
```

best

**Comment by KrKOo** [comment]
Hey @bpfrd 
that's a known issue of minikube when running multiple nodes. Please check out this [post](https://github.com/kubernetes/minikube/issues/12360#issuecomment-1430243861).
Basically you have to disables/enables some addons in minikube. Then you will also have to update your `values.yaml`, to use the `csi-hostpath-sc` storageclass.
